### ISSUE TITLE
Problem with GRASS r.series for whole directory

### ISSUE THREAD

**Issue by ctottrup** [TIGER-NET/WOIS_processing#2]
Unable to execute script “GRASS r.series for whole directory” (cf. workflow for medium resolution land degradation)

**Comment by radosuav** [comment]
There were two issues here. Firstly, the definition of r.series has changed and two input fields were removed. This was fixed in commit b7d529e8fae982e3102ccaa0febfaf3033d845f8. 

Secondly, there was a regression in the way algorithms are called from scripts in Processing. This affects the other scripts as well and has been fixed in commit c750b57e88a0ce89fe333e4358f6284f980e012e.
